name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: update-embeddings
  REPOSITORY_NAME: update-embeddings-repo
  IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/update-embeddings-repo/update-embeddings

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          pip install -r app/requirements.txt
          python -m unittest discover -s app/tests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Create Artifact Registry Repository if not exists
        run: |
          gcloud artifacts repositories create $REPOSITORY_NAME \
            --repository-format=docker \
            --location=$REGION \
            --description="Docker repository for update-embeddings" || true

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA -f Dockerfile .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$GITHUB_SHA

      - name: Deploy Cloud Run Job
        run: |
          gcloud beta run jobs create $SERVICE_NAME \
            --image $IMAGE_NAME:$GITHUB_SHA \
            --region $REGION \
            --set-secrets OPENAI_API_KEY=OPENAI_API_KEY:latest \
            --set-secrets PINECONE_API_KEY=PINECONE_API_KEY:latest \
            --set-env-vars GCS_BUCKET_NAME=my-pinecone-data-bucket-123,GCP_PROJECT_ID=$PROJECT_ID,PINECONE_ENVIRONMENT=default,PINECONE_INDEX_NAME=allmytext \
            --service-account $CLOUD_RUN_SA_EMAIL \
            --quiet



  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approv

