name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: update-embeddings
  REPOSITORY_NAME: update-embeddings-repo
  IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/update-embeddings-repo/update-embeddings
  CLOUD_RUN_SA_EMAIL: ${{ secrets.CLOUD_RUN_SA_EMAIL }} 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          pip install -r app/requirements.txt
          python -m unittest discover -s app/tests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GHACTIONS_GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Create Artifact Registry Repository if not exists
        run: |
          gcloud artifacts repositories create $REPOSITORY_NAME \
            --repository-format=docker \
            --location=$REGION \
            --description="Docker repository for update-embeddings" || true

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$GITHUB_SHA -f Dockerfile .

      - name: Tag Docker Image as Latest
        run: |
          docker tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:latest

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:$GITHUB_SHA
      
      - name: Push Docker Image as Latest
        run: |
          docker push $IMAGE_NAME:latest

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.TERRAFORM_GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          TF_VAR_pinecone_api_key: ${{ secrets.PINECONE_API_KEY }}
          TF_VAR_cloud_run_sa_email: ${{ secrets.CLOUD_RUN_SA_EMAIL }}
          TF_VAR_gcs_bucket_name: allmytext-data
          TF_VAR_image_name: us-central1-docker.pkg.dev/allmytext/update-embeddings-repo/update-embeddings
          TF_VAR_region: us-central1
          TF_VAR_service_name: update-embeddings
          TF_VAR_pinecone_environment: default
          TF_VAR_pinecone_index_name: allmytext
          TF_VAR_pinecone_api_key_secret: PINECONE_API_KEY
          TF_VAR_openai_api_key_secret: OPENAI_API_KEY
          TF_LOG: DEBUG
      
      - name: Handle Locking Errors
        if: (failure() || cancelled()) && contains(steps.apply.outputs.stderr, 'Error acquiring the state lock')
        run: |
          LOCK_ID=$(terraform show -json | jq -r '.values.root_module.resources[].values.id')
          terraform force-unlock $LOCK_ID
          terraform apply -auto-approve

